server:
  port: 8761

eureka:
  renewalPercentThreshold: 0.85
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

  server:
    wait-time-in-ms-when-sync-empty: 0
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false
    response-cache-update-interval-ms: 5000
